title: Weide Liu
position: Scientist
affiliation: A*star
email: liu_weide(at)i2r(dot)a-star(dot)edu(dot)sg or weide001(at)e(dot)ntu(dot)edu(dot)sg
keywords: minimal academic
google_scholar: https://scholar.google.co.uk/citations?user=QzsQSD0AAAAJ&hl=en
github_link: https://github.com/liuweide01
linkedin: https://www.linkedin.com/in/weide-liu-44352aa2/
avatar: ./assets/img/liuweide.jfif
google_analytics: G-7ETJRETJ5W
favicon: ./assets/img/ai_icon.png
favicon_dark: ./assets/img/ai_icon.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light